---
- hosts: ubuntu
  become: true


  tasks:


  - name: Install required packages for automount
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    loop:
      - autofs
      - nfs-common
      - python3

  - name: Add nfs.autofs to auto.master.d
    ansible.builtin.copy:
      src: ../files/nfs.autofs
      dest: /etc/auto.master.d/nfs.autofs
      owner: root
      mode: '0644'
    notify: Restart autofs

  - name: Add nfs mount map file
    ansible.builtin.copy:
      src: ../files/auto.nfs
      dest: /etc/auto.nfs
      owner: root
      mode: '0644'
    notify: Restart autofs

  - name: autofs service started
    ansible.builtin.systemd_service:
      name: autofs
      state: started
      enabled: true

  - name: copy service systemd
    ansible.builtin.copy:
      src: ../files/shared-http.service
      dest: /etc/systemd/system/shared-http.service
      mode: '0644'
    notify: reload http


  - name: activate and run service HTTP
    ansible.builtin.systemd:
      name: shared-http
      state: started
      enabled: yes


  handlers:

   - name: Restart autofs
     ansible.builtin.systemd_service:
       name: autofs
       state: restarted
  
   - name: reload http
     ansible.builtin.systemd_service:
       name: server http
       state: restarted
  

     
